export const dynamicFields = {
  fields: [
    {
      label: 'First Name',
      formControlName: 'firstName',
      type: 'text',
      placeholder: 'Enter your first name',
      required: true,
      validation: {
        required: true,
        minLength: 2,
        maxLength: 20,
      },
      errorMessages: {
        required: 'First name is required',
        minlength: 'First name must be at least 2 characters long',
        maxlength: 'First name cannot exceed 20 characters',
      },
    },
    {
      label: 'Last Name',
      formControlName: 'lastName',
      type: 'text',
      placeholder: 'Enter your last name',
      required: true,
      validation: {
        required: true,
        minLength: 2,
        maxLength: 20,
      },
      errorMessages: {
        required: 'Last name is required',
        minlength: 'Last name must be at least 2 characters long',
        maxlength: 'Last name cannot exceed 20 characters',
      },
    },
    {
      label: 'Email',
      formControlName: 'email',
      type: 'text',
      placeholder: 'Enter your email address',
      required: true,
      validation: {
        required: true,
        email: true,
      },
      errorMessages: {
        required: 'Email is required',
        email: 'Please enter a valid email address',
      },
    },
    {
      label: 'State',
      formControlName: 'state',
      type: 'select',
      placeholder: 'Select your state',
      required: true,
      options: [
        { value: 'AL', label: 'Alabama' },
        { value: 'AK', label: 'Alaska' },
        { value: 'AZ', label: 'Arizona' },
        { value: 'AR', label: 'Arkansas' },
        { value: 'CA', label: 'California' },
        { value: 'CO', label: 'Colorado' },
        { value: 'CT', label: 'Connecticut' },
        { value: 'DE', label: 'Delaware' },
        { value: 'FL', label: 'Florida' },
        { value: 'GA', label: 'Georgia' },
        { value: 'HI', label: 'Hawaii' },
        { value: 'ID', label: 'Idaho' },
        { value: 'IL', label: 'Illinois' },
        { value: 'IN', label: 'Indiana' },
        { value: 'IA', label: 'Iowa' },
        { value: 'KS', label: 'Kansas' },
        { value: 'KY', label: 'Kentucky' },
        { value: 'LA', label: 'Louisiana' },
        { value: 'ME', label: 'Maine' },
        { value: 'MD', label: 'Maryland' },
        { value: 'MA', label: 'Massachusetts' },
        { value: 'MI', label: 'Michigan' },
        { value: 'MN', label: 'Minnesota' },
        { value: 'MS', label: 'Mississippi' },
        { value: 'MO', label: 'Missouri' },
        { value: 'MT', label: 'Montana' },
        { value: 'NE', label: 'Nebraska' },
        { value: 'NV', label: 'Nevada' },
        { value: 'NH', label: 'New Hampshire' },
        { value: 'NJ', label: 'New Jersey' },
        { value: 'NM', label: 'New Mexico' },
        { value: 'NY', label: 'New York' },
        { value: 'NC', label: 'North Carolina' },
        { value: 'ND', label: 'North Dakota' },
        { value: 'OH', label: 'Ohio' },
        { value: 'OK', label: 'Oklahoma' },
        { value: 'OR', label: 'Oregon' },
        { value: 'PA', label: 'Pennsylvania' },
        { value: 'RI', label: 'Rhode Island' },
        { value: 'SC', label: 'South Carolina' },
        { value: 'SD', label: 'South Dakota' },
        { value: 'TN', label: 'Tennessee' },
        { value: 'TX', label: 'Texas' },
        { value: 'UT', label: 'Utah' },
        { value: 'VT', label: 'Vermont' },
        { value: 'VA', label: 'Virginia' },
        { value: 'WA', label: 'Washington' },
        { value: 'WV', label: 'West Virginia' },
        { value: 'WI', label: 'Wisconsin' },
        { value: 'WY', label: 'Wyoming' },
      ],
      errorMessages: {
        required: 'State is required',
      },
      validation: {
        required: true,
      },
    },
  ],
};
